# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f15c5db05c1a107b22cad5481aee6c770315d7adadf7ff4a5d1146443ac14e66027b8f600396e4fce93796b2532de51431bb84fc9be0b9c26f2dc729f322ea0b

test:
  secret_key_base: cf6d5b3dadcad1c971fe033db3322eacf237d6355054ea555e8371f752b51ceee3d8b4dec695509837839eb502bfc90c25b464a51f0a45dafe5d52585da8bcb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
